version: '2'

services:
  mysql:
    build: ./mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_DATABASE: db
        MYSQL_USER: siges
        MYSQL_PASSWORD: siges
        MYSQL_ROOT_PASSWORD: root

  php:
    build: ./php
    volumes:
      - ../:/var/www
    links:
      - mysql

  nginx:
    build: ./nginx
    volumes_from:
      - php
    ports:
      - "80:80"
    links:
      - php

  ### phpMyAdmin Container ####################################

  phpmyadmin:
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=siges
      - MYSQL_PASSWORD=siges
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "88:80"
    depends_on:
      - "mysql"
